replicaCount: 1

image:
  repository: openmf/fineract
  tag: "1.11.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: "1500m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

database:
  host: fineract-db-cluster-rw
  port: 5432
  username: postgres
  password: ""
  secretName: fineract-db-cluster-superuser
  secretKey: password

extraDatabases:
  - fineract_default
  - fineract_tenants

fineractEnv:
  FINERACT_SERVER_PORT: "8080"
  FINERACT_SERVER_SSL_ENABLED: "false"
  FINERACT_LOGGING_LEVEL: INFO
  JAVA_TOOL_OPTIONS: "-Xmx1536M -Xms512M"
  FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: org.postgresql.Driver
  FINERACT_DEFAULT_TENANTDB_TIMEZONE: Asia/Kolkata

probes:
  liveness:
    initialDelaySeconds: 240
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 120
    periodSeconds: 15

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: null
  targetMemoryUtilizationPercentage: null
