apiVersion: v1
kind: Service
metadata:
  name: fineract-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fineract-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
