apiVersion: v1
kind: Service
metadata:
  name: { { include "fineract-chart.fullname" . } }
  labels:
    app: fineract-server
spec:
  type: { { .Values.service.type } }
  selector:
    app: fineract-server
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: http
